server: 
    port: 9090
spring: 
    profiles: 
        active: prod
    redis: 
        database: 0
        host: 192.168.1.105
        password: 19941118
        port: 6379
        
        pool: 
            maxIdle: 8
            minIdle: 0  
            maxActive: 8  
            maxWait: -1  
            timeout: 60000
    rabbitmq: 
        host: 192.168.1.105
        port: 5672
        username: guest
        password: guest
    datasource: 
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/littleapp?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
        username: root
        password: 
        driverClassName: com.mysql.jdbc.Driver
        
        maximumPoolSize: 100
        maxIdle: 10
        maxWait: 10000
        minIdle: 5
        initialSize: 5
        validationQuery: SELECT 1
        testOnBorrow: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 18800
        
# ----------------------------------------
# ACTUATOR PROPERTIES
# ----------------------------------------
endpoints: 
  enabled: true
  sensitive: false
        
jwt:
  enable: false
  header: Authorization
  secret: 6IOh5rC46ZKi5LiN5piv5Yia
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
      
mybatis:
    typeAliasesPackage: ml.littleapp.model
    mapperLocations: classpath:mapper/*.xml

mapper:
    mappers:
        - ml.littleapp.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
# ----------------------------------------
# CRAWLER
# threadNum: number | single | auto
# ----------------------------------------
crawler:
    ip:
      init:
        threadNum: auto
      paging:
        threadNum: auto
      verify:
        threadNum: auto
      sources:
        - http://www.xicidaili.com/qq
        - http://www.xicidaili.com/wt
        - http://www.xicidaili.com/wn
        - http://www.xicidaili.com/nt
        - http://www.xicidaili.com/nn
        
    
