server: 
    port: 9090
logging:
    level:
        tk.mybatis: TRACE
spring: 
    datasource: 
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3307/test?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
        username: root
        password: 
        driverClassName: com.mysql.jdbc.Driver
        
        maximumPoolSize: 100
        maxIdle: 10
        maxWait: 10000
        minIdle: 5
        initialSize: 5
        validationQuery: SELECT 1
        testOnBorrow: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 18800
    profiles: 
        active: dev
mybatis:
    type-aliases-package: tk.mybatis.mapper.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - tk.mybatis.springboot.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql